# Generated by Django 4.2.5 on 2023-09-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='puser',
            new_name='user',
        ),
    ]
