# Generated by Django 4.2.5 on 2023-09-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_puser_postdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
